// src/lib/components/sections/footer.svelte

<div class="border-x mx-17.5 mr-17">
  <div class="relative z-0 bottom-0 left-17.5 w-full h-50 flex justify-center items-center">
    <div class="relative overflow-hidden w-full h-full flex justify-end px-12 text-right items-start py-12">
      <h2 class="absolute bottom-0 left-0 translate-y-1/3 sm:text-[192px] text-[80px] select-none font-serif">
        irazz
      </h2>
    </div>
  </div>
</div>

// apps/web/src/components/footer.tsx
export function Footer() {
  return (
    <div className="border-x mx-17.5 mr-17">
      <div className="relative z-0 bottom-0 left-17.5 w-full h-50 flex justify-center items-center">
        <div className="relative overflow-hidden w-full h-full flex justify-end px-12 text-right items-start py-12">
          <h2 className="absolute bottom-0 left-0 translate-y-1/3 sm:text-[192px] text-[80px] select-none font-serif">
            irazz
          </h2>
        </div>
      </div>
    </div>
  )
}
